# Generated by Django 5.1.15 on 2026-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_project_sampling_sort_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="sampling",
            field=models.CharField(
                choices=[
                    (
                        "Sequential sampling",
                        "Tasks are ordered by Data manager ordering",
                    ),
                    ("Uniform sampling", "Tasks are chosen randomly"),
                    (
                        "Uncertainty sampling",
                        "Tasks are chosen according to model uncertainty scores (active learning mode)",
                    ),
                    (
                        "Sorted sequential sampling",
                        "Tasks are sorted by user-specified task data fields",
                    ),
                ],
                default="Sequential sampling",
                max_length=100,
                null=True,
            ),
        ),
    ]
